---
abstract: 'High level email parsing and manipulation'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Test::Differences: 0
  Test::Fatal: 0
  Test::More: 0.88
  Test::Requires: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Courriel
requires:
  Carp: 0
  DateTime: 0
  DateTime::Format::Mail: 0
  DateTime::Format::Natural: 0
  Devel::PartialDump: 0
  Email::Abstract::Plugin: 0
  Email::Address: 0
  Email::MIME::Encodings: 0
  Email::MessageID: 0
  Encode: 0
  Exporter: 0
  File::Basename: 0
  File::LibMagic: 0
  File::Slurp: 0
  List::AllUtils: 0
  List::MoreUtils: 0.28
  MIME::Base64: 0
  MIME::QuotedPrint: 0
  Moose: 0
  Moose::Role: 0
  MooseX::Params::Validate: 0
  MooseX::Role::Parameterized: 0
  MooseX::StrictConstructor: 0
  MooseX::Types: 0
  MooseX::Types::Combine: 0
  MooseX::Types::Common::String: 0
  MooseX::Types::Moose: 0
  Scalar::Util: 0
  Sub::Exporter: 0
  namespace::autoclean: 0
  parent: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Courriel
  repository: git://git.urth.org/Courriel.git
version: 0.33
x_contributors:
  - 'Zbigniew Łukasiak <zzbbyy@gmail.com>'
