
BEGIN {
  unless ($ENV{AUTHOR_TESTING}) {
    require Test::More;
    Test::More::plan(skip_all => 'these tests are for testing by the author');
  }
}

use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006008
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
DROLSKY
DROLSKY's
Rolsky
Rolsky's
API
CPAN
Courriel
DateTime
Multipart
PayPal
Postel's
UTC
UTF
ascii
attribute's
cid
distro
filename
html
inline
lookup
multipart
utf
zh
Dave
autarch
Gregory
Oschwald
goschwald
Zbigniew
Łukasiak
zzbbyy
lib
Header
Part
Single
Builder
Types
Internal
Disposition
Role
HeaderWithAttributes
ContentType
Helpers
Streams
HeaderAttribute
Email
Abstract
Headers
